### ISSUE TITLE
TS2536: Type 'K' cannot be used to index type 'HTMLElementTagNameMap'

### ISSUE THREAD

**Issue by jamespsterling** [mostafizur044/angular-tradingview-widget#2]
Failure to compile using angular 12

```
Error: node_modules/angular-tradingview-widget/lib/tradingview-widget.component.d.ts:16:1186 - error TS2536: Type 'K' cannot be used to index type 'HTMLElementTagNameMap'
```

**Comment by dragonfihq** [comment]
been getting this error as well. Any fix for this one? (Angular 13)

![image](https://user-images.githubusercontent.com/104804309/198519401-da20ddd9-c702-406e-a6bf-8d9ec7b7ba99.png)

**Comment by mostafizur044** [comment]
Package upgradation done. Now it is compatible with latest angular. Please user new version and it is `1.0.0`.
